[package]
name = "tx3"
version = "0.0.1"
edition = "2021"

[dependencies]
async-compat = { version = "0.2.1", default-features = false }
bytes = { version = "1.1.0", default-features = false, features = [ "std" ] }
futures = { version = "0.3.21", default-features = false }
rustls = { version = "0.20.4", default-features = false }
tokio = { version = "1.17.0", default-features = false, features = [ "sync" ] }
tokio-rustls = { version = "0.23.3", default-features = false }
tokio-tungstenite = { version = "0.17.1", default-features = false }
yamux = { version = "0.10.1", default-features = false }

# optional
rcgen = { version = "0.9.2", default-features = false, optional = true }

[dev-dependencies]
rcgen = { version = "0.9.2", default-features = false }
rustls = { version = "0.20.4", default-features = false, features = [ "dangerous_configuration" ] }
tokio = { version = "1.17.0", features = [ "full" ] }

[package.metadata.docs.rs]
# build docs.rs page with all features enabled so we can see the APIs
all-features = true

[features]
default = []

dev_utils = [ "rcgen", "rustls/dangerous_configuration" ]
