name: Static Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  static-analysis:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Cargo Install Readme
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-readme

      - name: Make static
        run: make static
