name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cargo test
        uses: actions-rs/cargo@v1
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: DEBUG
        with:
          command: test
          args: --all-features --all-targets -- --test-threads 1
